name: Auto Duplicate PR to gov-prod

on:
  pull_request:
    branches:
      - prod
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  duplicate-pr:
    if: github.event.pull_request.base.ref == 'prod'
    runs-on: ubuntu-latest

    steps:
      - name: Create PR to gov-prod
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: gov-prod
          branch: ${{ github.head_ref }}
          title: "[GOV-PROD] ${{ github.event.pull_request.title }}"
          body: |
            üîÅ This PR was automatically created from #${{ github.event.pull_request.number }}

            ----------------------------------------
            Original PR Description:
            ${{ github.event.pull_request.body }}
          draft: false
